# ==========================================
# GIAI ĐOẠN 1: Dùng Node.js để build Frontend
# ==========================================
FROM node:20 AS node-builder

WORKDIR /app

# Copy các file package và cài đặt thư viện node_modules
COPY package*.json ./
RUN npm install

# Copy toàn bộ code vào và chạy lệnh build (Vite sẽ tạo ra thư mục public/build)
COPY . .
RUN npm run build

# ==========================================
# GIAI ĐOẠN 2: Dùng Alpine để siêu tối ưu dung lượng
# ==========================================
FROM php:8.2-fpm-alpine

WORKDIR /var/www

# Alpine không dùng 'apt-get' mà dùng 'apk' cực nhẹ, cài xong xóa cache luôn trong 1 dòng
RUN apk add --no-cache \
    git \
    curl \
    libpng-dev \
    libjpeg-turbo-dev \
    freetype-dev \
    oniguruma-dev \
    libxml2-dev \
    zip \
    unzip \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY . /var/www
COPY --from=node-builder /app/public/build /var/www/public/build

RUN chown -R www-data:www-data /var/www \
    && chmod -R 775 /var/www/storage /var/www/bootstrap/cache

EXPOSE 9000
CMD ["php-fpm"]
